### ISSUE TITLE
Dragstop event not triggered in touch mode?

### ISSUE THREAD

**Issue by Dylan190774** [kirillmurashov/vue-drag-resize#37] opened 2018-10-14 18:26 UTC
I'm having trouble understanding how `dragstop `works.

In this [example](https://codesandbox.io/s/qz99vj00pq) `dragstop` is being triggered immediately when the dragging stops (when the mouse button is released).

But when I use the _mobile emulator_ in Chrome, so I can try out touch-events, the `dragstop` event only fires  when I touch the screen outside the item, or when I touch the item again.

Is there a way to make this work in touch-mode too ?

**Comment by TitanFighter** [comment] 2018-10-15 10:30
1. This is a bug.
2. It can be manually fixed via:
  - `setInterval` + `@dragging` (for example start setInterval when dragging is started and compare every 0.5 sec old coordinates with new one -> no changes? -> dragging is ended + stop setInteval);
  - implement your own addEventListener('touchEnd', ...).

3. Taking into account your [task](https://github.com/kirillmurashov/vue-drag-resize/issues/36), you need to implement dropzone. For this purpose I would think [about this package](https://github.com/kutlugsahin/vue-smooth-dnd) instead.

**Comment by tpraxl** [comment] 2018-10-17 14:44
@TitanFighter Can you give details about the bug? Is it an implementation problem or a Chrome Touch Mode problem? I would try to fix this with a PR, but I can't seem to find the cause.

The vue-drag-resize implementation looks fine at the first glance:

```js
bodyUp() { 
   …
   this.$emit('dragging', this.rect);
   this.$emit('dragstop', this.rect);
   …
}
```
So I suppose, it's a Chrome Touch Mode problem?

**Comment by tpraxl** [comment] 2018-10-17 15:56
It was an implementation problem. Added a PR that fixes the bug.

**Comment by TitanFighter** [comment] 2018-12-03 16:19
@KoeketieneDesign It seems this component is abandoned. You can try to use original component [vue-draggable-resizable](https://github.com/mauricius/vue-draggable-resizable) (especially v2 from dev branch, because v1 does not support reactive props).

**Comment by tpraxl** [comment] 2018-12-04 11:19
@TitanFighter Thanks for the tip.

**Closed** 2019-01-01 14:48 UTC
